name: Ejecutar main.py semanalmente

on:
  schedule:
    - cron: '04 7 * * 5'  # Cada viernes a las 06:58 UTC 2 horas menos
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest
#    environment: RESERVA_LOWFIT

#    env:
#      USER: ${{ secrets.USER }}
#      PASSWORD: ${{ secrets.PASSWORD }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run main.py
        run: python main.py